Fix delete expired token
gaidds/React-crm-project pull request #62
Opened 2024-10-14 09:33 UTC by gaidds

### Implement Token Deletion from Local Storage on Expiration

**Description:** This pull request implements the automatic deletion of the token from local storage after it expires.

**How to Test:**
1. The current expiration time in our backend is set to 24 hours. To test this branch, navigate to the backend and update the expiration time in settings.py. Change it for example to 2 minutes as follows:
`"ACCESS_TOKEN_LIFETIME": timedelta(minutes=2)`

2. After making this change, log in to the application.

3. Wait for 2 minutes. You should be redirected to the Login page, and the token will no longer be present in local storage.

2024-10-15 13:36 UTC, Ashraf-Alshashaa approved these changes
Thanks, It's work perfectly.
Just we need to delete the org after logout.

2024-10-15 13:52 UTC, Ashraf-Alshashaa requested changes

2024-10-15 13:52 UTC, Ashraf-Alshashaa commented on src/components/TokenExpirationHandler.tsx
> +        localStorage.removeItem('TokenExpiration');
add remove org plz

2024-10-16 07:17 UTC, gaidds commented on src/components/TokenExpirationHandler.tsx
> +        localStorage.removeItem('TokenExpiration');
I added org deletion

2024-10-16 07:46 UTC, Ashraf-Alshashaa approved these changes

2024-10-16 07:48 UTC, merged